"use client";
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {motion,useScroll,useTransform,useReducedMotion,type MotionValue} from 'framer-motion';
import {ArrowUpRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import assets from '@/lib/assets.json';
import {portfolio,services} from '@/lib/portfolio';
function FadeIn({children,delay=0,x=0,y=30,className=''}:{children:ReactNode;delay?:number;x?:number;y?:number;className?:string}){const reduced=useReducedMotion();return <motion.div className={className} initial={reduced?false:{opacity:0,x,y}} whileInView={{opacity:1,x:0,y:0}} viewport={{once:true,margin:'50px',amount:0}} transition={{delay,duration:.7,ease:[.25,.1,.25,1]}}>{children}</motion.div>}
function Magnet({children}:{children:ReactNode}){const ref=useRef<HTMLDivElement>(null);const [position,setPosition]=useState({x:0,y:0,active:false});const reduced=useReducedMotion();useEffect(()=>{if(reduced||!matchMedia('(pointer:fine)').matches)return;function move(e:MouseEvent){const r=ref.current?.getBoundingClientRect();if(!r)return;const x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;const active=Math.abs(x)<r.width/2+150&&Math.abs(y)<r.height/2+150;setPosition({x:active?x/3:0,y:active?y/3:0,active})}function reset(){setPosition({x:0,y:0,active:false})}window.addEventListener('mousemove',move,{passive:true});document.addEventListener('mouseleave',reset);return()=>{window.removeEventListener('mousemove',move);document.removeEventListener('mouseleave',reset)}},[reduced]);return <div ref={ref}><div style={{transform:`translate3d(${position.x}px,${position.y}px,0)`,transition:position.active?'transform .3s ease-out':'transform .6s ease-in-out',willChange:'transform'}}>{children}</div></div>}
function Character({char,index,total,progress}:{char:string;index:number;total:number;progress:MotionValue<number>}){const opacity=useTransform(progress,[index/total,(index+1)/total],[.2,1]);return <span className="character"><span aria-hidden="true" style={{visibility:'hidden'}}>{char}</span><motion.span aria-hidden="true" style={{opacity,position:'absolute',inset:0}}>{char}</motion.span></span>}
function AnimatedText(){const ref=useRef<HTMLParagraphElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:['start 0.8','end 0.2']});const reduced=useReducedMotion();const text=portfolio.about;let index=0;return <p ref={ref} className="about-copy" aria-label={text}>{reduced?text:text.split(' ').map((word,i)=><span className="word" key={i}>{[...word+' '].map(char=><Character key={index} char={char} index={index++} total={text.length} progress={scrollYProgress}/>)}</span>)}</p>}
function MarqueeSection(){const ref=useRef<HTMLElement>(null);const rows=useRef<(HTMLDivElement|null)[]>([]);const reduced=useReducedMotion();useEffect(()=>{if(reduced)return;let frame=0;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{if(!ref.current)return;const offset=(window.innerHeight-ref.current.getBoundingClientRect().top)*.3;rows.current.forEach((r,i)=>{if(r)r.style.transform=`translateX(${i?-(offset-200)-4320:offset-200-4752}px)`})})};update();window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',update);window.removeEventListener('resize',update)}},[reduced]);return <section ref={ref} className="marquee" aria-label="Motion and digital design inspiration">{[assets.marquee.slice(0,11),assets.marquee.slice(11)].map((row,i)=><div className="marquee-row" ref={el=>{rows.current[i]=el}} key={i}>{[...row,...row,...row].map((src,j)=><img key={j} src={src} alt={j<row.length?`Motion design exploration ${i*11+j+1}`:''} aria-hidden={j>=row.length} width="420" height="270" loading="lazy" onError={e=>{if(e.currentTarget.src!==assets.marquee[0])e.currentTarget.src=assets.marquee[0]}}/>)}</div>)}</section>}
function ProjectCard({index,onOpen}:{index:number;onOpen:(i:number)=>void}){const ref=useRef<HTMLDivElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:['start start','end start']});const scale=useTransform(scrollYProgress,[0,1],[1,1-(2-index)*.03]);const reduced=useReducedMotion();const project=portfolio.projects[index];return <div ref={ref} className="project-track"><motion.article className="project-card" style={{scale:reduced?1:scale,top:`calc(var(--card-top) + ${index*28}px)`}}><header className="project-header"><span className="project-number">0{index+1}</span><div className="project-title"><span>{project.category}</span><h3>{project.name}</h3></div>{project.url?<a className="live-button" href={project.url} target="_blank" rel="noreferrer">Live Project <ArrowUpRight size={18}/></a>:<button className="live-button" onClick={()=>onOpen(index)}>Live Project <ArrowUpRight size={18}/></button>}</header><div className="project-images"><div>{assets.projectImages.slice(index*3,index*3+2).map((src,j)=><img key={src} src={src} alt={`${project.name} — detail ${j+1}`} loading="lazy"/>)}</div><img src={assets.projectImages[index*3+2]} alt={`${project.name} — main artwork`} loading="lazy"/></div></motion.article></div>}
export default function Home(){const [dialog,setDialog]=useState<number|null>(null);const contact=()=>setDialog(-1);function ContactButton(){return <button className="contact-button" onClick={contact}>Contact Me</button>};return <main><section className="hero"><FadeIn delay={0} y={-20}><nav aria-label="Main navigation"><a href="#about">About</a><a href="#price">Price</a><a href="#projects">Projects</a><button onClick={contact}>Contact</button></nav></FadeIn><FadeIn delay={.15} y={40}><h1 className="hero-heading">Hi, i'm jack</h1></FadeIn><div className="portrait"><FadeIn delay={.6} y={30}><Magnet><img alt="Jack — 3D creator portrait" src={assets.portrait} fetchPriority="high"/></Magnet></FadeIn></div><div className="hero-bottom"><FadeIn delay={.35} y={20}><p>a 3d creator driven by crafting striking and unforgettable projects</p></FadeIn><FadeIn delay={.5} y={20}><ContactButton/></FadeIn></div></section><MarqueeSection/><section id="about" className="about section"><div className="decorations" aria-hidden="true">{assets.decorations.map((src,i)=><FadeIn key={src} className={`decoration decoration-${i}`} x={i<2?-80:80} y={0} delay={[.1,.25,.15,.3][i]}><img src={src} alt="" loading="lazy"/></FadeIn>)}</div><div className="about-content"><FadeIn y={40}><h2 className="hero-heading">About me</h2></FadeIn><AnimatedText/><FadeIn><ContactButton/></FadeIn></div></section><section id="price" className="services section"><FadeIn><h2>Services</h2></FadeIn><div className="service-list">{services.map((s,i)=><FadeIn delay={i*.1} key={s.name}><article className="service"><span className="service-number">0{i+1}</span><div><h3>{s.name}</h3><p>{s.description}</p></div></article></FadeIn>)}</div></section><section id="projects" className="projects section"><FadeIn><h2 className="hero-heading">Project</h2></FadeIn><div className="project-list">{portfolio.projects.map((p,i)=><ProjectCard key={p.name} index={i} onOpen={setDialog}/>)}</div></section><Dialog open={dialog!==null} onOpenChange={open=>{if(!open)setDialog(null)}}><DialogContent className="contact-dialog"><DialogTitle>{dialog===-1?"Let's create something incredible.":dialog!==null?portfolio.projects[dialog].name:''}</DialogTitle><DialogDescription>{dialog===-1?(portfolio.email?'Tell me about your next project.':'Contact details coming soon.'):'The live project link is coming soon.'}</DialogDescription>{dialog===-1&&portfolio.email&&<a className="contact-button" href={`mailto:${portfolio.email}`}>Email Jack <ArrowUpRight size={16}/></a>}</DialogContent></Dialog></main>}

