'use client';
import {ArrowLeft,ArrowUpRight,ArrowDown} from 'lucide-react';
import {motion,useReducedMotion} from 'framer-motion';
import type {ReactNode} from 'react';
import {ZezeSlice,ZEZE_ARTWORK} from '@/components/zeze-artwork';
const benefits=[['01','高效','约140°弯曲针齿深入毛层，集中带走浮毛'],['02','省心','一键退毛设计，减少手抠毛发'],['03','舒适','圆润针头降低拉扯与刮蹭'],['04','通用','猫狗、长短毛均可使用']];
const colors=[['Soft Beige','#F0EAE2'],['Warm Sand','#D6C6B7'],['Light Yellow','#F7E8AA'],['Sunflower Yellow','#FFD638'],['ZEZE Green','#91AA37']];
const workflow=[['INSIGHT','卖点分析'],['VISUAL DIRECTION','视觉方向确定'],['AI GENERATION','AI 场景与视觉生成'],['RETOUCHING','产品一致性与细节修正'],['LAYOUT','详情页排版输出']];
function Reveal({children,className=''}:{children:ReactNode;className?:string}){const reduced=useReducedMotion();return <motion.div className={className} initial={reduced?false:{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.08}} transition={{duration:.4,ease:'easeOut'}}>{children}</motion.div>}
function Label({number,children}:{number:string;children:ReactNode}){return <p className="case-eyebrow"><span>{number}</span>{children}</p>}
function Module({kind,number,title,note,className=''}:{kind:'kv'|'pain'|'pins'|'clean'|'universal'|'details'|'specs';number:string;title:string;note:string;className?:string}){return <Reveal className={`case-module ${className}`}><figure><ZezeSlice module={kind} alt={`ZEZE 详情页设计 — ${title}`}/><figcaption><span>{number} / {title}</span><small>{note}</small></figcaption></figure></Reveal>}
export default function ZezeCase(){const reduced=useReducedMotion();return <main className="zeze-case">
<header className="case-nav"><a href="/#zeze-case"><ArrowLeft size={16}/> BACK TO PORTFOLIO</a><span>CASE STUDY / 05</span></header>
<section className="case-overview" id="overview"><Reveal className="overview-copy"><Label number="01">PROJECT OVERVIEW</Label><h1>ZEZE PET<br/><span>GROOMING</span></h1><h2>太阳花去浮毛梳</h2><p className="case-subtitle">E-commerce Detail Page</p><p className="case-discipline">Product Strategy / Visual Design / AI Image Generation</p><dl className="case-facts"><div><dt>项目类型</dt><dd>电商详情页</dd></div><div><dt>职责</dt><dd>视觉设计 / 卖点梳理 / AIGC视觉生成</dd></div><div><dt>品类</dt><dd>宠物护理</dd></div><div><dt>输出</dt><dd>商品详情页 / 场景视觉 / 卖点视觉</dd></div></dl><a className="case-button" href="#full-page">浏览完整设计 <ArrowUpRight size={18}/></a></Reveal><Reveal className="overview-art"><span className="art-index">ZEZE / PRODUCT VISUAL</span><div className="phone-preview"><ZezeSlice module="kv" eager alt="手机中展示的 ZEZE 电商详情页首屏"/></div><span className="art-note">A little sunshine.<br/>A little less shedding.</span></Reveal></section>
<nav className="case-index" aria-label="案例章节">{[['strategy','02 / STRATEGY'],['visual-system','03 / VISUAL SYSTEM'],['key-modules','04 / KEY MODULES'],['full-page','05 / FULL PAGE'],['workflow','06 / WORKFLOW']].map(([id,label])=><a key={id} href={`#${id}`}>{label}<ArrowDown size={12}/></a>)}</nav>
<section className="case-section strategy-section" id="strategy"><Reveal><Label number="02">DESIGN STRATEGY</Label><div className="case-heading-row"><h2>一梳去浮毛，<br/>日常护理更省心<span className="yellow-dot">.</span></h2><p>从日常掉毛的真实困扰出发，<br/>将产品结构转化为易于理解的护理体验。</p></div></Reveal><div className="strategy-focus"><Reveal className="angle-panel"><span className="tiny-label">THE CORE PRODUCT STORY</span><motion.div className="angle-number" initial={reduced?false:{opacity:0,scale:.95}} whileInView={{opacity:1,scale:1}} viewport={{once:true}} transition={{duration:.4}}>140<span>°</span></motion.div><span className="angle-caption">CURVED PIN DESIGN</span><p>弯曲针齿 · 从结构优势到视觉记忆</p></Reveal><Reveal className="strategy-image"><ZezeSlice module="pins" alt="140°弯曲针齿卖点设计：针齿深入毛层，集中带走浮毛"/></Reveal></div><div className="benefit-grid">{benefits.map(([n,title,copy])=><Reveal key={n} className="benefit"><span>{n}</span><h3>{title}</h3><p>{copy}</p></Reveal>)}</div></section>
<section className="case-section visual-section" id="visual-system"><Reveal><Label number="03">VISUAL SYSTEM</Label><div className="case-heading-row"><h2>柔和底色。<br/>鲜明的产品记忆。</h2><p>以米色与暖沙色建立亲和感；<br/>太阳花黄和 ZEZE 绿作为识别重点。</p></div></Reveal><Reveal className="palette">{colors.map(([name,hex])=><div key={name} className="color-swatch" style={{background:hex}}><span>{hex}</span><h3>{name}</h3></div>)}</Reveal><p className="palette-note">COLOR DIRECTION / 根据作品视觉整理的展示色板</p><div className="phone-stage"><div className="phone-stage-copy"><span className="tiny-label">DESIGNED FOR THE SCROLL</span><h3>从第一眼，<br/>到每一个卖点。</h3><p>信息清晰，产品突出。<br/>让用户在手机上自然读懂设计。</p><span className="stage-tag">MOBILE COMMERCE / ZEZE</span></div><Reveal className="phone-duo"><div className="phone-preview phone-one"><ZezeSlice module="kv" alt="手机展示：太阳花宠物梳首屏视觉"/></div><div className="phone-preview phone-two"><ZezeSlice module="clean" alt="手机展示：一键退毛卖点视觉"/></div></Reveal></div></section>
<section className="case-section" id="key-modules"><Reveal><Label number="04">KEY MODULES</Label><div className="case-heading-row"><h2>从痛点切入，<br/>用视觉解释产品。</h2><p>场景建立共鸣，结构说明价值，<br/>细节与参数承接购买决策。</p></div></Reveal><div className="module-grid"><Module kind="kv" number="01" title="首屏主视觉" note="FIRST IMPRESSION" className="module-kv"/><Module kind="pain" number="02" title="消费者痛点" note="THE EVERYDAY PROBLEM" className="module-pain"/><div className="module-editorial"><span>LESS SHEDDING.</span><span>MORE <em>CARE.</em></span><p>把复杂的产品信息，<br/>变成清晰的购买理由。</p></div><Module kind="pins" number="03" title="140°弯曲针齿" note="THE HERO FEATURE" className="module-pins"/><Module kind="clean" number="04" title="一键退毛" note="ONE-CLICK CLEANING" className="module-clean"/><Module kind="universal" number="05" title="猫狗通用" note="EVERYDAY COMPANION" className="module-universal"/><Reveal className="module-details"><div className="details-duo"><ZezeSlice module="details" alt="产品细节：圆润针头、140°针齿与退毛结构"/><ZezeSlice module="specs" alt="ZEZE 太阳花去浮毛梳产品信息与尺寸参数"/></div><div className="details-caption"><span>06 / 产品细节与参数</span><small>DETAILS THAT BUILD CONFIDENCE</small></div></Reveal></div></section>
<section className="case-section full-page-section" id="full-page"><Reveal><Label number="05">FULL PAGE DESIGN</Label><div className="case-heading-row"><h2>完整详情页。</h2><p>从首屏到产品参数，<br/>从左至右，三段连贯呈现完整设计。</p></div></Reveal><div className="full-page-meta"><span>ZEZE / E-COMMERCE DETAIL PAGE</span><a href={ZEZE_ARTWORK} target="_blank" rel="noopener noreferrer">查看原图 <ArrowUpRight size={14}/></a></div><div className="full-page-triptych" aria-label="完整详情页，按左、中、右顺序阅读">{[0,1,2].map(part=><figure className="full-page-panel" key={part}><figcaption><span>0{part+1}</span><span>ZEZE / DETAIL DESIGN</span></figcaption><a className="full-page-segment" href={ZEZE_ARTWORK} target="_blank" rel="noopener noreferrer" aria-label={`查看完整详情页原图，第 ${part+1} 段`}><img src={ZEZE_ARTWORK} width={675} height={9548} style={{top:`${-part*100}%`}} alt={`ZEZE 完整详情页第 ${part+1} 段，共三段`} loading="lazy"/></a></figure>)}</div></section>
<section className="case-section workflow-section" id="workflow"><Reveal><Label number="06">AIGC WORKFLOW</Label><div className="case-heading-row"><h2>AI 参与生成，<br/>设计决定方向。</h2><p>从卖点分析到最终排版，<br/>让每一张视觉服务于产品表达。</p></div></Reveal><ol className="workflow-list">{workflow.map(([en,cn],i)=><Reveal key={en} className="workflow-step"><li><span className="workflow-number">0{i+1}</span><h3>{en}</h3><p>{cn}</p>{i<4&&<span className="workflow-arrow" aria-hidden="true">→</span>}</li></Reveal>)}</ol><div className="case-end"><span>05 / ZEZE — E-COMMERCE DESIGN</span><a href="/#zeze-case" className="case-button"><ArrowLeft size={16}/> 返回作品集</a><a href="#overview" className="back-to-top">BACK TO TOP ↑</a></div></section>
</main>}
